language: objective-c
osx_image: xcode9.1
env:
  - DESTINATION="OS=11.1,name=iPhone 7" SCHEME="Vote"

before_install:
  - gem install cocoapods -v '1.3.1'

script:
- xcodebuild clean build -workspace Vote.xcworkspace -scheme "$SCHEME"
- xcodebuild test -workspace Vote.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION"
