language: objective-c
osx_image: xcode9.1

before_install:
- brew update 
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -workspace Vote/Vote.xcworkspace -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild test -workspace Vote/Vote.xcworkspace -scheme "$SCHEME" | xcpretty -c
