language: objective-c
osx_image: xcode8
env:
  - DESTINATION="OS=11.0,name=iPhone 7" SCHEME="Vote" SDK=iphonesimulator11.0

before_install:
- brew update 
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -workspace Vote/Vote.xcworkspace -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild test -workspace Vote/Vote.xcworkspace -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" | xcpretty -c
